package org.twitterissimo.tools;

public enum ConnectionMessage {
    SIGN_UP, SIGN_IN, BAD_EMAIL, BAD_PASSWORD,
    UNABLE_TO_CONNECT, BAD_BIRTHDAY, GET_POSTS, NEW_POST, DEL_POST, UPDATE_POSTS, UPDATED_PROFILE, GET_ALL_POSTS, GET_FRIENDS_POSTS, NEW_LIKE, DELETE_USER, ID_BY_LOCATION
}